format_version: 3
pipelines:
  ansible:
    group: ops
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    environment_variables:
      COMMAND: ansible --version
    materials:
      deploy:
        git: https://github.com/ss19901101/infrastructure.git
        shallow_clone: true
        auto_update: true
        branch: master
        destination: deploy
    stages:
    - run:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
          allow_only_on_success: false
        jobs:
          run:
            timeout: 0
            tasks:
            - plugin:
                configuration:
                  id: script-executor
                  version: '1'
                options:
                  script: |-
                    cd deploy
                    gocd/run_ansible.sh "$COMMAND"
                run_if: passed
